services:
  user-service-db:
    image: postgres:16
    container_name: user-service-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: $POSTGRESQL_DATABASE
      POSTGRES_USER: $POSTGRESQL_USERNAME
      POSTGRES_PASSWORD: $POSTGRESQL_PASSWORD
    networks:
      - delivery-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRESQL_USERNAME" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    env_file:
      - .env
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: $KEYCLOAK_ADMIN_USERNAME
      KC_BOOTSTRAP_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: false
    command: start-dev --import-realm
    volumes:
      - ./docker-compose/keycloak:/opt/keycloak/data/import:ro
    ports:
      - "8090:8080"
    networks:
      - delivery-network
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /realms/master HTTP/1.1\r\nHost: localhost\r\n\r\n' >&3 && cat <&3 | grep -q '200 OK'" ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s


  user-service:
    image: mykhailokornukh/user-service:latest
    container_name: user-service
    restart: always
    depends_on:
      user-service-db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_NAME: "user-service"
      SPRING_DATASOURCE_URL: $POSTGRESQL_DATABASE_URL
      SPRING_DATASOURCE_USERNAME: $POSTGRESQL_USERNAME
      SPRING_DATASOURCE_PASSWORD: $POSTGRESQL_PASSWORD
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: $SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
      KEYCLOAK_SERVER_URL: $KEYCLOAK_SERVER_URL
      KEYCLOAK_ADMIN_REALM: $KEYCLOAK_ADMIN_REALM
      KEYCLOAK_ADMIN_CLIENT_ID: $KEYCLOAK_ADMIN_CLIENT_ID
      KEYCLOAK_REALM: $KEYCLOAK_REALM
      KEYCLOAK_CLIENT_ID: $KEYCLOAK_CLIENT_ID
      KEYCLOAK_ISSUER_URI: $KEYCLOAK_ISSUER_URI
      KEYCLOAK_JWK_SET_URI: $KEYCLOAK_JWK_SET_URI
    ports:
      - "8081:8081"
    networks:
      - delivery-network

networks:
  delivery-network:
    driver: bridge
